### ISSUE TITLE
Zły nawias przy przyciskach w action=models&page=1&p_id=6

### ISSUE THREAD

**Issue by interduo** [jarecky/lms#10]
Literówka, jest {trans{.
Przy przyciskach 'usuń' i 'klonuj'.

**Comment by jarecky** [comment]
Nie mogę tego znaleźć...

**Comment by interduo** [comment]
![blad_trans](https://cloud.githubusercontent.com/assets/17087236/18904296/a8ad4206-855d-11e6-95b0-54b6c8978543.png)

Spójrz na kursor myszy. Tutaj :)
