### ISSUE TITLE
Brak logiki portów typu "COMBO" w urządzeniach aktywnych

### ISSUE THREAD

**Issue by interduo** [jarecky/lms#11]
Jak w temacie:
Porty COMBO to porty typu copper/optical z tym że medium światłowodowe ma priorytet wyłacza miedź (zależnie od producenta).

Zadeklarowane podłaczenie światła do tego portu powinno domyślnie zajmować również port COPPER.
Tak żeby nie popełnić gaf.

**Comment by jarecky** [comment]
No tak. Portów combo nie przewidywaliśmy...
