### ISSUE TITLE
Obowiązek wyboru typu urządzenia przy predefiniowanych zestawach

### ISSUE THREAD

**Issue by interduo** [jarecky/lms#7]
"First select type of device !!!!!"

Muszę definiować typ urządzenia skoro zamierzam go wybrać z predefiniowanych zestawów?

**Comment by jarecky** [comment]
Teoretycznie - wybierasz typ i potem masz dopiero liste predefiniowanych zestawów dla danego typu - w zamierzeniu miało być to tylko dla urządzeń aktywnych i elementów pasywnych.

**Comment by interduo** [comment]
A czy typ mógłby się ładować z predefiniowanych zestawów słownika?
