### ISSUE TITLE
Wybór typów portów i dostępne technologie do wyboru  

### ISSUE THREAD

**Issue by interduo** [jarecky/lms#8]
Przy wyborze typu "copper" nie powinienem mieć do wyboru CDMA i innych radiowych.

![ports](https://cloud.githubusercontent.com/assets/17087236/18868356/31ab9cd0-84a8-11e6-824b-a6441f8ecf36.png)

Pozatym znikła ramka tutaj też i nie ma etykiety Typ przy nowodowanych pozycjach.

**Comment by interduo** [comment]
I brak technologi RS232 (port konsolowy COM).

**Comment by jarecky** [comment]
No dobra. Po co Ci port konsolowy COM przy paszportyzacji sieci (pytam się poważnie).

**Comment by interduo** [comment]
Chciałem tylko zaznaczyć, że istnieje taki port (bo wygląda jak skrętkowy) później może to jakoś wyjść.
Z kilku corowych switchy mam podciągnięte console port pod serwer (ale to mało istotne).
